# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7d01158d56a666cfc2b94e6d751fcbed6fbcfa006086e0ab6b24ecb6c7f3e329db73bf405c0fc812a30393b1d03386efc7a8c6ae202e921eb62d9571094e14

test:
  secret_key_base: 4b0bc2688c132a0e0fc44d1ebb647fc71b97fae87a9c8b71db3223d0150285b5b7563bd6a5c2fb659d686fb28e96d1afe2c66aa349f1c1ad5a7eff0bb5c018e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
